config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "dashboard#index", as: :root
    resources :users
    resources :channels
    resources :messages
  end

  get "dashboard/index"

  resource :profile,
    only: %i[show edit update]

  resources :channels do
    resources :messages
  end

  resources :memberships
  resources :servers
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :server

  has_many :messages, dependent: :destroy
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1 or /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy!

    respond_to do |format|
      format.html { redirect_to channels_path, status: :see_other, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.expect(channel: [ :server_id, :name, :topic, :channel_type ])
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>">
  <p>
    <strong>Server:</strong>
    <%= channel.server_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= channel.name %>
  </p>

  <p>
    <strong>Topic:</strong>
    <%= channel.topic %>
  </p>

  <p>
    <strong>Channel type:</strong>
    <%= channel.channel_type %>
  </p>

</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :server_id, style: "display: block" %>
    <%= form.text_field :server_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :topic, style: "display: block" %>
    <%= form.textarea :topic %>
  </div>

  <div>
    <%= form.label :channel_type, style: "display: block" %>
    <%= form.number_field :channel_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<% content_for :title, "Editing channel" %>

<h1>Editing channel</h1>

<%= render "form", channel: @channel %>

<br>

<div>
  <%= link_to "Show this channel", @channel %> |
  <%= link_to "Back to channels", channels_path %>
</div>

app/views/channels/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Channels" %>

<h1>Channels</h1>

<div id="channels">
  <% @channels.each do |channel| %>
    <%= render channel %>
    <p>
      <%= link_to "Show this channel", channel %>
    </p>
  <% end %>
</div>

<%= link_to "New channel", new_channel_path %>

app/views/channels/new.html.erb
<% content_for :title, "New channel" %>

<h1>New channel</h1>

<%= render "form", channel: @channel %>

<br>

<div>
  <%= link_to "Back to channels", channels_path %>
</div>

app/views/channels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @channel %>

<div>
  <%= link_to "Edit this channel", edit_channel_path(@channel) %> |
  <%= link_to "Back to channels", channels_path %>

  <%= button_to "Destroy this channel", @channel, method: :delete %>
</div>