config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "dashboard#index", as: :root
    resources :users
    resources :channels
    resources :messages
  end

  get "dashboard/index"

  resource :profile,
    only: %i[show edit update]

  resources :channels do
    resources :messages
  end

  resources :memberships
  resources :servers
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :server

  enum :role, { owner: 0, admin: 1, member: 2 }
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[ show edit update destroy ]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy!

    respond_to do |format|
      format.html { redirect_to memberships_path, status: :see_other, notice: "Membership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.expect(membership: [ :user_id, :server_id, :role, :joined_at ])
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :server_id, style: "display: block" %>
    <%= form.text_field :server_id %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :joined_at, style: "display: block" %>
    <%= form.datetime_field :joined_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

  <p>
    <strong>Server:</strong>
    <%= membership.server_id %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= membership.role %>
  </p>

  <p>
    <strong>Joined at:</strong>
    <%= membership.joined_at %>
  </p>

</div>

app/views/memberships/edit.html.erb
<% content_for :title, "Editing membership" %>

<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Memberships" %>

<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<% content_for :title, "New membership" %>

<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>