config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "dashboard#index", as: :root
    resources :users
    resources :channels
    resources :messages
  end

  get "dashboard/index"

  resource :profile,
    only: %i[show edit update]

  resources :channels do
    resources :messages
  end

  resources :memberships
  resources :servers
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/server.rb
class Server < ApplicationRecord
  has_one_attached :icon

  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: %i[ show edit update destroy ]

  # GET /servers or /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1 or /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers or /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: "Server was successfully created." }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1 or /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: "Server was successfully updated." }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1 or /servers/1.json
  def destroy
    @server.destroy!

    respond_to do |format|
      format.html { redirect_to servers_path, status: :see_other, notice: "Server was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def server_params
      params.expect(server: [ :name, :description, :public, :icon ])
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server) do |form| %>
  <% if server.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
        <% server.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.checkbox :public %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/_server.html.erb
<div id="<%= dom_id server %>">
  <p>
    <strong>Name:</strong>
    <%= server.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= server.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= server.public %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= server.icon %>
  </p>

</div>

app/views/servers/edit.html.erb
<% content_for :title, "Editing server" %>

<h1>Editing server</h1>

<%= render "form", server: @server %>

<br>

<div>
  <%= link_to "Show this server", @server %> |
  <%= link_to "Back to servers", servers_path %>
</div>

app/views/servers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Servers" %>

<h1>Servers</h1>

<div id="servers">
  <% @servers.each do |server| %>
    <%= render server %>
    <p>
      <%= link_to "Show this server", server %>
    </p>
  <% end %>
</div>

<%= link_to "New server", new_server_path %>

app/views/servers/new.html.erb
<% content_for :title, "New server" %>

<h1>New server</h1>

<%= render "form", server: @server %>

<br>

<div>
  <%= link_to "Back to servers", servers_path %>
</div>

app/views/servers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @server %>

<div>
  <%= link_to "Edit this server", edit_server_path(@server) %> |
  <%= link_to "Back to servers", servers_path %>

  <%= button_to "Destroy this server", @server, method: :delete %>
</div>